const historyKey = "zahlenabgleich-history";
    const state = { runs: 10, round: 0, startedAt: 0, tick: null, results: [], answerLocked: false, usedValues: new Set() };
    const $ = (id) => document.getElementById(id);
    const history = () => JSON.parse(localStorage.getItem(historyKey) || "[]");
    const formatTime = (seconds) => `${seconds.toFixed(1).replace(".", ",")} s`;
    const randomDigits = (length) => Array.from({ length }, () => Math.floor(Math.random() * 10)).join("");
    const randomAddress = () => `${["Berg", "Linden", "Wiesen", "Hafen", "Morgen"][Math.floor(Math.random() * 5)]}straße ${Math.floor(Math.random() * 180) + 1}, ${Math.floor(Math.random() * 8) + 1}${randomDigits(4).slice(1)} ${["Köln", "Bremen", "Ulm", "Jena"][Math.floor(Math.random() * 4)]}`;
    function slightlyDifferent(value) {
      const positions = Array.from(value, (character, index) => /[0-9A-Za-zÄÖÜäöüß]/.test(character) ? index : -1).filter((index) => index >= 0);
      const index = positions[Math.floor(Math.random() * positions.length)];
      const character = value[index];
      const replacement = /[0-9]/.test(character) ? String((Number(character) + 1 + Math.floor(Math.random() * 9)) % 10) : character === character.toUpperCase() ? String.fromCharCode(65 + (character.charCodeAt(0) - 65 + 1) % 26) : String.fromCharCode(97 + (character.charCodeAt(0) - 97 + 1) % 26);
      return `${value.slice(0, index)}${replacement}${value.slice(index + 1)}`;
    }
    function uniqueValue(generator) {
      let value;
      do { value = generator(); } while (state.usedValues.has(value));
      state.usedValues.add(value);
      return value;
    }
    function newPair() {
      const address = Math.random() > .5; const same = Math.random() > .48; const generator = address ? randomAddress : () => randomDigits(8);
      const left = uniqueValue(generator); let right = left;
      if (!same) { do { right = slightlyDifferent(left); } while (state.usedValues.has(right)); state.usedValues.add(right); }
      $("round-type").textContent = address ? "Adressprüfung" : "Nummernprüfung"; $("left-value").textContent = left; $("right-value").textContent = right;
      state.correct = same ? "same" : "different"; state.startedAt = performance.now(); state.answerLocked = false; $("status").textContent = "Taste 1 oder 2 drücken"; $("status").className = "status";
    }
    function startGame() { state.runs = Number($("run-slider").value); state.round = 0; state.results = []; state.usedValues = new Set(); $("waiting").hidden = true; $("finish").hidden = true; $("active-game").hidden = false; newPair(); updateGameUi(); clearInterval(state.tick); state.tick = setInterval(() => { $("timer").textContent = formatTime((performance.now() - state.startedAt) / 1000); }, 80); }
    function updateGameUi() { $("round-label").textContent = `Durchlauf ${state.round + 1} von ${state.runs}`; $("progress-bar").style.width = `${(state.round / state.runs) * 100}%`; }
    function answer(value) { if (state.answerLocked || $("active-game").hidden) return; state.answerLocked = true; const elapsed = (performance.now() - state.startedAt) / 1000; const correct = value === state.correct; state.results.push(elapsed); const status = $("status"); status.textContent = correct ? `Richtig · ${formatTime(elapsed)}` : `Weiter · ${formatTime(elapsed)}`; status.className = `status ${correct ? "good" : "bad"}`; state.round++; updateGameUi(); setTimeout(() => state.round >= state.runs ? finishGame() : newPair(), 280); }
    function finishGame() { clearInterval(state.tick); const average = state.results.reduce((a, b) => a + b, 0) / state.results.length; const data = history(); data.push({ average, date: new Date().toISOString() }); localStorage.setItem(historyKey, JSON.stringify(data.slice(-30))); $("progress-bar").style.width = "100%"; $("active-game").hidden = true; $("finish").hidden = false; $("finish-average").textContent = formatTime(average); updateProgress(); }
    function updateProgress() { const data = history(); $("games-metric").textContent = data.length; if (!data.length) { $("average-metric").textContent = $("best-metric").textContent = "—"; $("empty-chart").hidden = false; $("progress-chart").hidden = true; return; } const values = data.map((item) => item.average); $("average-metric").textContent = formatTime(values.reduce((a, b) => a + b, 0) / values.length); $("best-metric").textContent = formatTime(Math.min(...values)); $("empty-chart").hidden = true; $("progress-chart").hidden = false; drawChart(values); }
    function drawChart(values) { const canvas = $("progress-chart"), ratio = window.devicePixelRatio || 1, width = canvas.clientWidth, height = canvas.clientHeight; canvas.width = width * ratio; canvas.height = height * ratio; const ctx = canvas.getContext("2d"); ctx.scale(ratio, ratio); const pad = { top: 26, right: 24, bottom: 35, left: 48 }, max = Math.max(...values) * 1.18 || 1, min = Math.max(0, Math.min(...values) * .82), x = (i) => pad.left + (i / Math.max(1, values.length - 1)) * (width - pad.left - pad.right), y = (v) => pad.top + (1 - (v - min) / (max - min || 1)) * (height - pad.top - pad.bottom); ctx.font = "12px Trebuchet MS"; ctx.strokeStyle = "#d8e2df"; ctx.fillStyle = "#6b7d82"; ctx.lineWidth = 1; for (let i = 0; i < 4; i++) { const gy = pad.top + i * (height - pad.top - pad.bottom) / 3; ctx.beginPath(); ctx.moveTo(pad.left, gy); ctx.lineTo(width - pad.right, gy); ctx.stroke(); ctx.fillText(formatTime(max - i * (max - min) / 3), 0, gy + 4); } ctx.strokeStyle = "#087f79"; ctx.lineWidth = 3; ctx.beginPath(); values.forEach((value, i) => i ? ctx.lineTo(x(i), y(value)) : ctx.moveTo(x(i), y(value))); ctx.stroke(); values.forEach((value, i) => { ctx.fillStyle = "#ed765e"; ctx.beginPath(); ctx.arc(x(i), y(value), 4, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = "#6b7d82"; ctx.fillText(i + 1, x(i) - 3, height - 10); }); }
    $("run-slider").addEventListener("input", (event) => { $("run-count").textContent = event.target.value; }); $("start-button").addEventListener("click", startGame); $("again-button").addEventListener("click", startGame); document.querySelectorAll(".answer").forEach((button) => button.addEventListener("click", () => answer(button.dataset.answer))); document.addEventListener("keydown", (event) => { if (event.key === "1") answer("same"); if (event.key === "2") answer("different"); }); $("clear-history").addEventListener("click", () => { localStorage.removeItem(historyKey); updateProgress(); }); document.querySelectorAll(".tab").forEach((tab) => tab.addEventListener("click", () => { document.querySelectorAll(".tab, .view").forEach((item) => item.classList.remove("active")); tab.classList.add("active"); $(tab.dataset.view).classList.add("active"); if (tab.dataset.view === "progress") updateProgress(); })); window.addEventListener("resize", () => { if (history().length) drawChart(history().map((item) => item.average)); }); updateProgress();